name: Reload Docker Image

on:
  workflow_dispatch:
  # 你也可以根据需要设置其他触发条件，例如定时触发或当代码被推送到某个分支时自动触发

jobs:
  reload-image:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx (optional for pull and run)
      uses: docker/setup-buildx-action@v2
      # 注意：对于简单的 pull 和 run 操作来说，这一步可能是可选的

    # 停止旧容器的步骤（假设容器名为 iptv-api-container）
    - name: Stop old container (if exists)
      run: docker stop iptv-api-container || true
      # 使用 || true 来忽略当容器不存在时的错误

    # 删除旧容器的步骤（可选，但推荐执行以确保不会留下悬挂的容器）
    - name: Remove old container (if exists)
      run: docker rm iptv-api-container || true

    # 拉取新镜像的步骤
    - name: Pull new Docker image
      run: docker pull guovern/iptv-api:latest

    # 运行新容器的步骤
    # 注意：你需要根据镜像的实际需求来调整这里的运行命令
    - name: Run new container
      run: docker run -d --name iptv-api-container -p 8080:80 guovern/iptv-api:latest
      # -d 表示以守护进程模式运行容器
      # --name 指定容器的名称
      # -p 8000:80 将容器的 80 端口映射到主机的 8080 端口

    # 你可以在这里添加更多的步骤，例如执行测试、发送通知等
